+incdir+$AXI4_AVIP_BASE_DIR/src/hdl_top/master_agent_bfm
+incdir+$AXI4_AVIP_BASE_DIR/src/hdl_top/slave_agent_bfm
+incdir+$AXI4_AVIP_BASE_DIR/src/hdl_top/axi4_interface
$AXI4_AVIP_BASE_DIR/src/hdl_top/axi4_interface/axi4_if.sv
$AXI4_AVIP_BASE_DIR/src/hdl_top/master_agent_bfm/axi4_master_driver_bfm.sv
$AXI4_AVIP_BASE_DIR/src/hdl_top/master_agent_bfm/axi4_master_monitor_bfm.sv
$AXI4_AVIP_BASE_DIR/src/hdl_top/master_agent_bfm/axi4_master_agent_bfm.sv
$AXI4_AVIP_BASE_DIR/src/hdl_top/slave_agent_bfm/axi4_slave_driver_bfm.sv
$AXI4_AVIP_BASE_DIR/src/hdl_top/slave_agent_bfm/axi4_slave_monitor_bfm.sv
$AXI4_AVIP_BASE_DIR/src/hdl_top/slave_agent_bfm/axi4_slave_agent_bfm.sv
$AXI4_AVIP_BASE_DIR/src/hdl_top/master_assertions.sv
$AXI4_AVIP_BASE_DIR/src/hdl_top/slave_assertions.sv
$AXI4_AVIP_BASE_DIR/src/hdl_top/hdl_top.sv
